# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1396, 802)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-60, -30, 1471, 871))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/HP/OneDrive/Desktop/jarvis ui/Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1070, 330, 311, 91))
        self.pushButton.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 30pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:7px solid blue;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1080, 690, 301, 101))
        self.pushButton_3.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 30pt \"Algerian\";\n"
"border:7px solid red;\n"
"color:red;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.Text_Time = QtWidgets.QTextBrowser(Form)
        self.Text_Time.setGeometry(QtCore.QRect(1070, 500, 301, 91))
        self.Text_Time.setStyleSheet("background:Transparent;\n"
"border:none;\n"
"")
        self.Text_Time.setObjectName("Text_Time")
        self.Text_Temp = QtWidgets.QTextBrowser(Form)
        self.Text_Temp.setGeometry(QtCore.QRect(20, 730, 81, 61))
        self.Text_Temp.setStyleSheet("background:Transparent;\n"
"border:none;")
        self.Text_Temp.setObjectName("Text_Temp")
        self.text_Date = QtWidgets.QTextBrowser(Form)
        self.text_Date.setGeometry(QtCore.QRect(150, 730, 291, 61))
        self.text_Date.setStyleSheet("background:Transparent;\n"
"border:none;")
        self.text_Date.setObjectName("text_Date")
        self.Youtube_button = QtWidgets.QPushButton(Form)
        self.Youtube_button.setGeometry(QtCore.QRect(20, 340, 231, 61))
        self.Youtube_button.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Youtube_button.setObjectName("Youtube_button")
        self.Chrome_button = QtWidgets.QPushButton(Form)
        self.Chrome_button.setGeometry(QtCore.QRect(270, 420, 221, 61))
        self.Chrome_button.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Chrome_button.setObjectName("Chrome_button")
        self.Whatshapp = QtWidgets.QPushButton(Form)
        self.Whatshapp.setGeometry(QtCore.QRect(20, 420, 231, 61))
        self.Whatshapp.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Whatshapp.setObjectName("Whatshapp")
        self.gif3 = QtWidgets.QLabel(Form)
        self.gif3.setGeometry(QtCore.QRect(480, 20, 481, 301))
        self.gif3.setStyleSheet("border:2px solid blue;")
        self.gif3.setText("")
        self.gif3.setPixmap(QtGui.QPixmap("C:/Users/HP/Downloads/Iron_Template_1.gif"))
        self.gif3.setScaledContents(True)
        self.gif3.setObjectName("gif3")
        self.gif4 = QtWidgets.QLabel(Form)
        self.gif4.setGeometry(QtCore.QRect(500, 340, 551, 441))
        self.gif4.setStyleSheet("border:2px solid blue;")
        self.gif4.setText("")
        self.gif4.setPixmap(QtGui.QPixmap("C:/Users/HP/Downloads/live (1).gif"))
        self.gif4.setScaledContents(True)
        self.gif4.setObjectName("gif4")
        self.gif1 = QtWidgets.QLabel(Form)
        self.gif1.setGeometry(QtCore.QRect(20, 20, 451, 301))
        self.gif1.setStyleSheet("border:2px solid blue;")
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("C:/Users/HP/OneDrive/Desktop/jarvis ui/gifloader.gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.Whatshapp_2 = QtWidgets.QPushButton(Form)
        self.Whatshapp_2.setGeometry(QtCore.QRect(270, 500, 221, 61))
        self.Whatshapp_2.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Whatshapp_2.setObjectName("Whatshapp_2")
        self.Whatshapp_3 = QtWidgets.QPushButton(Form)
        self.Whatshapp_3.setGeometry(QtCore.QRect(270, 340, 221, 61))
        self.Whatshapp_3.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Whatshapp_3.setObjectName("Whatshapp_3")
        self.Whatshapp_4 = QtWidgets.QPushButton(Form)
        self.Whatshapp_4.setGeometry(QtCore.QRect(20, 500, 231, 61))
        self.Whatshapp_4.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Whatshapp_4.setObjectName("Whatshapp_4")
        self.Whatshapp_5 = QtWidgets.QPushButton(Form)
        self.Whatshapp_5.setGeometry(QtCore.QRect(20, 580, 231, 61))
        self.Whatshapp_5.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Whatshapp_5.setObjectName("Whatshapp_5")
        self.Whatshapp_6 = QtWidgets.QPushButton(Form)
        self.Whatshapp_6.setGeometry(QtCore.QRect(270, 580, 221, 61))
        self.Whatshapp_6.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"")
        self.Whatshapp_6.setObjectName("Whatshapp_6")
        self.Whatshapp_7 = QtWidgets.QPushButton(Form)
        self.Whatshapp_7.setGeometry(QtCore.QRect(10, 660, 481, 61))
        self.Whatshapp_7.setStyleSheet("background-color:rgb(0,0,0);\n"
"font: 18pt \"Algerian\";\n"
"color:rgb(0,255,255);\n"
"border:3px solid blue;\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"")
        self.Whatshapp_7.setObjectName("Whatshapp_7")
        self.gif2 = QtWidgets.QLabel(Form)
        self.gif2.setGeometry(QtCore.QRect(970, 20, 411, 301))
        self.gif2.setStyleSheet("border:2px solid blue;")
        self.gif2.setText("")
        self.gif2.setPixmap(QtGui.QPixmap("C:/Users/HP/OneDrive/Desktop/jarvis ui/f1.gif"))
        self.gif2.setScaledContents(True)
        self.gif2.setObjectName("gif2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "START"))
        self.pushButton_3.setText(_translate("Form", "EXIT"))
        self.Youtube_button.setText(_translate("Form", "Youtube"))
        self.Chrome_button.setText(_translate("Form", "Chrome"))
        self.Whatshapp.setText(_translate("Form", "Whatsapp"))
        self.Whatshapp_2.setText(_translate("Form", "Wikipidea"))
        self.Whatshapp_3.setText(_translate("Form", "Spotify"))
        self.Whatshapp_4.setText(_translate("Form", "Alarm"))
        self.Whatshapp_5.setText(_translate("Form", "Book_pdf\'s"))
        self.Whatshapp_6.setText(_translate("Form", "Maps"))
        self.Whatshapp_7.setText(_translate("Form", "Language_Translator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
